---
- name: "Calculate facts for {{ new_name }}"
  set_fact:
    dir: "{{ libvirt_domain_definition_dir }}/{{ new_name }}"
    name: "{{ new_name }}"
  vars:
    new_name: "{{ (libvirt_domain.definition.content|selectattr('name', 'equalto', 'name')|first).content | mandatory }}"

- name: "Create directory for {{ name }}"
  file:
    path: "{{ dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "Write domain definition for {{ name }}"
  copy:
    dest: "{{ dir }}/definition.json"
    content: "{{ libvirt_domain.definition | to_nice_json }} "
    owner: root
    group: root
    mode: 0644
  register: dom_def

- name: "Apply domain definition for {{ name }}"
  command:
    argv:
      - define_dom_from_json
      - "{{ dir }}/definition.json"
  when: dom_def.changed

- name: "Place extra files for {{ name }}"
  copy: "{{ extra_file | combine({ 'dest': dir + '/' + extra_file.dest }) }}"
  loop: "{{ libvirt_domain.extra_files | default([]) }}"
  loop_control:
    loop_var: extra_file